sudo: required
services:
  - docker

before_install:
  - docker build -t samjbro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samjbro/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t samjbro/practice-multi-client ./client
  - docker build -t samjbro/practice-multi-nginx ./nginx
  - docker build -t samjbro/practice-multi-server ./server
  - docker build -t samjbro/practice-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push samjbro/practice-multi-client
  - docker push samjbro/practice-multi-nginx
  - docker push samjbro/practice-multi-server
  - docker push samjbro/practice-multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-230836431314
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY